service: serverless-ruby
package:
  exclude:
    - packaging/**

provider:
  name: aws
  runtime: nodejs4.3
  versionFunctions: false # optional, default is true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get